In [4]:
import tensorflow as tf

# 张量排序

 * sort/argsort 得到序列排序/得到序列排序后的位置
 * topk 得到前n个大数（小数）
 * top-5 acc

## sort/argsort

In [7]:
a = tf.random.shuffle(tf.range(5))
a

<tf.Tensor: id=14, shape=(5,), dtype=int32, numpy=array([1, 2, 4, 0, 3], dtype=int32)>

In [9]:
# 降序排列
tf.sort(a, direction="DESCENDING")

<tf.Tensor: id=31, shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0], dtype=int32)>

In [10]:
# 获得降序排列后的相对原数据的位置
tf.argsort(a, direction="DESCENDING")

<tf.Tensor: id=41, shape=(5,), dtype=int32, numpy=array([2, 4, 1, 0, 3], dtype=int32)>

In [14]:
tf.gather(a, tf.argsort(a, direction="DESCENDING"))

<tf.Tensor: id=63, shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0], dtype=int32)>

In [21]:
a = tf.random.uniform([3, 3], maxval=10, dtype=tf.int32)
a

<tf.Tensor: id=91, shape=(3, 3), dtype=int32, numpy=
array([[1, 9, 7],
       [6, 0, 7],
       [9, 1, 6]], dtype=int32)>

In [24]:
tf.sort(a), tf.sort(a, direction="DESCENDING")

(<tf.Tensor: id=133, shape=(3, 3), dtype=int32, numpy=
 array([[1, 7, 9],
        [0, 6, 7],
        [1, 6, 9]], dtype=int32)>,
 <tf.Tensor: id=141, shape=(3, 3), dtype=int32, numpy=
 array([[9, 7, 1],
        [7, 6, 0],
        [9, 6, 1]], dtype=int32)>)

In [25]:
tf.argsort(a)

<tf.Tensor: id=152, shape=(3, 3), dtype=int32, numpy=
array([[0, 2, 1],
       [1, 0, 2],
       [1, 2, 0]], dtype=int32)>

## topk

In [27]:
a = tf.random.uniform([3, 3], maxval=10, dtype=tf.int32)
a

<tf.Tensor: id=160, shape=(3, 3), dtype=int32, numpy=
array([[4, 4, 8],
       [6, 8, 8],
       [8, 4, 2]], dtype=int32)>

In [32]:
res = tf.math.top_k(a, k=2)
res

(TopKV2(values=<tf.Tensor: id=174, shape=(3, 2), dtype=int32, numpy=
 array([[8, 4],
        [8, 8],
        [8, 4]], dtype=int32)>, indices=<tf.Tensor: id=175, shape=(3, 2), dtype=int32, numpy=
 array([[2, 0],
        [1, 2],
        [0, 1]], dtype=int32)>),
 <tf.Tensor: id=175, shape=(3, 2), dtype=int32, numpy=
 array([[2, 0],
        [1, 2],
        [0, 1]], dtype=int32)>)

In [35]:
res.indices, res.values

(<tf.Tensor: id=175, shape=(3, 2), dtype=int32, numpy=
 array([[2, 0],
        [1, 2],
        [0, 1]], dtype=int32)>,
 <tf.Tensor: id=174, shape=(3, 2), dtype=int32, numpy=
 array([[8, 4],
        [8, 8],
        [8, 4]], dtype=int32)>)

#### top accuracy

In [36]:
prob = tf.constant([[0.1, 0.2, 0.7], [0.2, 0.7, 0.1]])
target = tf.constant([2, 0])
k_b = tf.math.top_k(prob, k=3).indices
k_b

<tf.Tensor: id=180, shape=(2, 3), dtype=int32, numpy=
array([[2, 1, 0],
       [1, 0, 2]], dtype=int32)>

In [39]:
k_b = tf.transpose(k_b, perm=[1, 0])
k_b

<tf.Tensor: id=186, shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [1, 0],
       [0, 2]], dtype=int32)>

In [44]:
target = tf.broadcast_to(target, [3, 2])
target

<tf.Tensor: id=195, shape=(3, 2), dtype=int32, numpy=
array([[2, 0],
       [2, 0],
       [2, 0]], dtype=int32)>

In [43]:
tf.equal(k_b, target)

<tf.Tensor: id=193, shape=(3, 2), dtype=bool, numpy=
array([[ True, False],
       [False,  True],
       [False, False]])>