In [1]:
import tensorflow as tf

In [28]:
# zeros, 接收 shape 参数
tf.zeros([]), tf.zeros([1]), tf.zeros([2,2])

(<tf.Tensor: id=47, shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: id=50, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: id=53, shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>)

In [31]:
# zeros_like 接收 tensor 参数
tensor_0 = tf.zeros([1])
# zeros_like(tensor) = tf.zeros(tensor.shape)
tf.zeros_like(tensor_0), tf.zeros(tensor_0.shape)

(<tf.Tensor: id=68, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: id=71, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>)

In [35]:
# ones 初始化为1
tf.ones([]), tf.ones([1]), tf.ones([2, 2])

(<tf.Tensor: id=93, shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: id=96, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 <tf.Tensor: id=99, shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>)

In [37]:
# ones_like 使用方法和 zeros_like 相同
tensor_1 = tf.ones([1])
tf.ones_like(tensor_1), tf.ones(tensor_1.shape)

(<tf.Tensor: id=114, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 <tf.Tensor: id=117, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)

In [40]:
# fill
tf.fill([2, 2], 3)

<tf.Tensor: id=123, shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 3]], dtype=int32)>

In [45]:
# random
# 正态分布
tf.random.normal([2, 2], mean=1, stddev=1)

<tf.Tensor: id=153, shape=(2, 2), dtype=float32, numpy=
array([[1.4304217 , 0.79954505],
       [0.7178713 , 0.80752563]], dtype=float32)>

In [46]:
tf.random.normal([2, 2])

<tf.Tensor: id=159, shape=(2, 2), dtype=float32, numpy=
array([[ 0.28808996, -0.4033764 ],
       [ 0.5063527 , -0.08805122]], dtype=float32)>

In [50]:
tf.random.truncated_normal([2, 2], mean=0, stddev=1), tf.random.normal([2, 2], mean=0, stddev=1)

(<tf.Tensor: id=195, shape=(2, 2), dtype=float32, numpy=
 array([[-0.567653  ,  0.81972235],
        [ 0.652435  ,  0.23261236]], dtype=float32)>,
 <tf.Tensor: id=201, shape=(2, 2), dtype=float32, numpy=
 array([[ 1.4613687 , -0.72407055],
        [ 0.42065078, -0.9017768 ]], dtype=float32)>)

In [52]:
# 均匀分布
tf.random.uniform([2, 2], minval=0, maxval=1)

<tf.Tensor: id=215, shape=(2, 2), dtype=float32, numpy=
array([[0.09196353, 0.2152592 ],
       [0.19122493, 0.45572293]], dtype=float32)>

In [54]:
# 洗牌
test = tf.range(4)
test, tf.random.shuffle(test)

(<tf.Tensor: id=224, shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>,
 <tf.Tensor: id=225, shape=(4,), dtype=int32, numpy=array([3, 0, 1, 2], dtype=int32)>)

In [55]:
# constant
tf.constant(1)

<tf.Tensor: id=226, shape=(), dtype=int32, numpy=1>

In [56]:
tf.constant([1, 2])

<tf.Tensor: id=227, shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [60]:
# scalar（标量） 
# 例子 loss
out = tf.random.uniform([4, 10])
print(out)
y = tf.range(4)
print(y)
y = tf.one_hot(y, depth=10)
y

tf.Tensor(
[[0.58692205 0.4736625  0.80797064 0.36966205 0.97114766 0.4265102
  0.54153955 0.63531446 0.25944316 0.31613684]
 [0.97994924 0.9321933  0.262406   0.71045387 0.91622734 0.8881396
  0.13285911 0.5271834  0.78588486 0.23172617]
 [0.23103893 0.25278997 0.2449857  0.2976365  0.7820029  0.20999205
  0.67267954 0.20734131 0.4823612  0.41061544]
 [0.18766654 0.33322585 0.952335   0.02627242 0.1294111  0.7163553
  0.91120017 0.12144613 0.3007574  0.0677985 ]], shape=(4, 10), dtype=float32)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


<tf.Tensor: id=275, shape=(4, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [62]:
loss = tf.keras.losses.mse(y, out)
loss

<tf.Tensor: id=281, shape=(4,), dtype=float32, numpy=array([0.31736377, 0.41336498, 0.23283067, 0.34713444], dtype=float32)>

In [64]:
loss = tf.reduce_mean(loss)
loss

<tf.Tensor: id=285, shape=(), dtype=float32, numpy=0.32767347>

In [80]:
# Vector（向量）
net = tf.keras.layers.Dense(10)
net.build([4, 8])
net.kernel, net.bias

(<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
 array([[-0.50782835,  0.45434272, -0.08679199,  0.00891042, -0.24358162,
         -0.16048363, -0.5199071 ,  0.5460819 ,  0.48889148, -0.3551987 ],
        [-0.53178406, -0.57356447,  0.38989997, -0.56900996, -0.5464729 ,
          0.37682742, -0.55512595,  0.34949732,  0.09919065, -0.29205763],
        [ 0.34532046,  0.31033826, -0.31892216,  0.04482383,  0.0902099 ,
         -0.24197441, -0.2882619 ,  0.27160972,  0.30062765, -0.49175802],
        [-0.34935004, -0.4113738 ,  0.23513424, -0.13449538, -0.0212723 ,
          0.47638416, -0.15632725, -0.1358796 ,  0.56086755, -0.499385  ],
        [ 0.1765688 ,  0.13830817, -0.07759032, -0.15973619,  0.17576289,
         -0.00966918,  0.48621428, -0.53306794, -0.36685956,  0.09367013],
        [ 0.39550167,  0.44574285, -0.41681063, -0.46715826,  0.46964526,
         -0.0372178 , -0.30854574,  0.04425204, -0.46592367, -0.53373814],
        [-0.21966517, -0.48979375, -0.5223282