In [39]:
import tensorflow as tf
import numpy as np

In [14]:
array = tf.range(4)
print(array)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


In [27]:
print('ndim: {}'.format(array.ndim))
print('device: {}'.format(array.device))

ndim: 1
device: /job:localhost/replica:0/task:0/device:CPU:0


In [17]:
# 查看维度
tf.rank(array)

<tf.Tensor: id=50, shape=(), dtype=int32, numpy=1>

In [34]:
# 创建3维数组
test = tf.ones([1, 2, 2])
tf.rank(test)

<tf.Tensor: id=98, shape=(), dtype=int32, numpy=3>

In [30]:
isinstance(array, tf.Tensor)

True

In [32]:
# 推荐使用该方法判断对象是否为 tensor
tf.is_tensor(array)

True

In [33]:
array.dtype

tf.int32

In [44]:
# np 转 tensor
np_a = np.arange(4)
tensor_a = tf.convert_to_tensor(np_a)
np_a, tensor_a

(array([0, 1, 2, 3]),
 <tf.Tensor: id=102, shape=(4,), dtype=int64, numpy=array([0, 1, 2, 3])>)

In [46]:
tensor_a = tf.convert_to_tensor(np_a, dtype=tf.int32)
tensor_a

<tf.Tensor: id=104, shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [52]:
tf.cast(tensor_a, dtype=tf.float32)

<tf.Tensor: id=110, shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>

In [54]:
tf.cast(tensor_a, dtype=tf.double)

<tf.Tensor: id=112, shape=(4,), dtype=float64, numpy=array([0., 1., 2., 3.])>

In [61]:
b = tf.constant([0, 1])
bb = tf.cast(b, tf.bool)
bb, tf.cast(bb, tf.int32)

(<tf.Tensor: id=126, shape=(2,), dtype=bool, numpy=array([False,  True])>,
 <tf.Tensor: id=127, shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>)

In [64]:
# tf.Variable
t_a = tf.range(4)
t_a

<tf.Tensor: id=154, shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [68]:
v_a = tf.Variable(t_a)
v_a, v_a.dtype, v_a.name

(<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>,
 tf.int32,
 'Variable:0')

In [70]:
v_a = tf.Variable(v_a, name="test")
v_a.name, v_a.trainable

('test:0', True)

In [72]:
# isinstance 方法判断 Variable 类型不是 Tensor，而 tf.is_tensor 可以，所以不推荐使用 isinstance 方法判断类型
isinstance(v_a, tf.Tensor), isinstance(v_a, tf.Variable), tf.is_tensor(v_a)

(False, True, True)

In [75]:
# tensor 转 numpy 类型
v_a.numpy()

array([0, 1, 2, 3], dtype=int32)

In [77]:
# 对于标量来说，可以直接用数据类型转换
test_scalar = tf.ones([])
test_scalar

<tf.Tensor: id=188, shape=(), dtype=float32, numpy=1.0>

In [78]:
int(test_scalar) # 直接使用 int，float

1